





# Footer Settings
# --------------------------------------
footer:
  owner:
    enable: true
    since: 2022
  custom_text:
  copyright: true # Copyright of theme and framework
  ICP: # Chinese ICP License
    enable: true
    url:
    text: 桂ICP备2020007847号-1
    icon: /img/icp.png
